#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <getopt.h>
#include <pthread.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <netinet/ip.h>
#include <netinet/tcp.h>
#include <netinet/ip_icmp.h>
#include <arpa/inet.h>
#include <fcntl.h>
#include <netdb.h>
#include <errno.h>
#include <time.h>
#include <pcap.h>
#include <limits.h>
#include <ifaddrs.h>
#include <net/if.h>
#include <net/route.h>
#include <sys/ioctl.h>
#include <net/ethernet.h>
#include <netinet/udp.h>
#include <ctype.h>
#include <stdbool.h>
#include <netinet/ip_icmp.h>
#ifdef __linux__
#include <linux/if_packet.h>
#endif
#include "linux_compat.h"